title = "Cowie.me"
base_url = "https://cowie.me"
default_language = "en"
description = ""

compile_sass = true

generate_rss = true
rss_limit = 100

highlight_code = true
highlight_theme = "monokai"

generate_tags_pages = true
generate_categories_pages = true

[extra]
subtitle = ""
author = { name = "Matthew Cowie", email = "matthew@cowie.me" }
